<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="8.0.26" />
    <PackageReference Include="RestSharp" Version="106.12.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="RoomColliderData\TestAreaScene-index1.collision">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
